
name: Deploy to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ‚úÖ PEM CRU (sem base64)
      - name: Prepare SSH key (raw PEM)
        shell: bash
        run: |
          mkdir -p ~/.ssh
          printf '%s' "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}   # admin
          port: 22
          key_path: ~/.ssh/id_rsa
          script_stop: true
          debug: true
          script: |
            set -e
            cd /opt/hello-devops

            git fetch origin
            git reset --hard origin/master

            # üîê Dica: se der "permission denied" no docker, troque para sudo docker (veja abaixo)
            docker build -t hello-devops:latest .
            docker rm -f hello-devops || true

            # Ajuste a porta da direita conforme a porta INTERNA da sua app (ex: 3000)
            docker run -d --name hello-devops --restart unless-stopped -p 80:3000 hello-devops:latest

            docker ps
            curl -I http://localhost:80
``
